#pre-commit-config.yaml for trunk and terraform
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.5.3
    hooks:
      - id: prettier
        additional_dependencies: [prettier-plugin-toml]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
      - id: check-ast
      - id: check-symlinks
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: v0.20.0
    hooks:
      - id: terraform-docs
        args: ["--output", "markdown", "--output-file", "README.md"]
  - repo: https://github.com/terraform-linters/tflint
    rev: v0.58.0
    hooks:
      - id: tflint
        args: ["--enable", "terraform_docs"]
